#!/usr/bin/env bash

: "${VM_NAME:=el10}"
: "${VM_HOSTNAME:=el10}"
: "${VM_FQDN:=el10.ajm.dev}"
: "${VM_USERNAME:=ajm}"
: "${VM_CPUS:=8}"
: "${VM_MEMORY_MB:=16384}"
: "${VM_DISK_GB:=300}"
: "${VM_TIMEZONE:=Europe/London}"
: "${VM_KEYBOARD_LAYOUT:=gb}"
: "${VM_KEYBOARD_MODEL:=pc105}"
: "${VM_KEYBOARD_VARIANT:=mac_intl}"
: "${VM_KEYBOARD_OPTIONS:=}"
: "${VM_KEYBOARD_VC_KEYMAP:=gb-mac_intl}"
: "${VM_K8S_CHANNEL:=v1.35}"
: "${VM_CHRONY_MAKESTEP:=1.0 3}"
: "${VM_PACKAGE_UPDATE:=true}"
: "${VM_PACKAGE_UPGRADE:=true}"
: "${VM_PACKAGE_REBOOT_IF_REQUIRED:=true}"
: "${VM_DISABLE_FIREWALLD:=true}"
: "${VM_IMAGE_ARTIFACTS_URL:=https://www.mirrorservice.org/sites/download.rockylinux.org/pub/rocky/10/images/${VM_ARCH}/}"
: "${VM_IMAGE_NAME_GLOB:=Rocky-10-GenericCloud-Base-*.${VM_ARCH}.qcow2}"
: "${VM_IMAGE_NAME_REGEX:=Rocky-10-GenericCloud-Base-[^\"]*\\.${VM_ARCH}\\.qcow2}"
: "${VM_CHECKSUM_NAME_GLOB:=CHECKSUM}"
: "${VM_CHECKSUM_NAME_REGEX:=CHECKSUM}"
: "${VM_PRL_DISTRIBUTION:=rhel}"
: "${VM_SSH_KEY_PATH:=${HOME}/.ssh/id_rsa.pub}"
: "${VM_HOME_BASE:=${HOME}/Parallels}"

: "${VM_NET_COUNT:=3}"

: "${VM_NET_0_NAME:=eth-shared}"
: "${VM_NET_0_TYPE:=shared}"
: "${VM_NET_0_PRL_IFACE:=}"
: "${VM_NET_0_MAC:=001C42E11010}"
: "${VM_NET_0_IPV4_METHOD:=static}"
: "${VM_NET_0_IPV4_ADDRESS:=10.211.55.130/24}"
: "${VM_NET_0_IPV4_GATEWAY:=}"
: "${VM_NET_0_IPV4_DNS:=}"
: "${VM_NET_0_ROUTE_METRIC:=200}"
: "${VM_NET_0_NEVER_DEFAULT:=yes}"

: "${VM_NET_1_NAME:=eth-real}"
: "${VM_NET_1_TYPE:=bridged}"
: "${VM_NET_1_PRL_IFACE:=Wi-Fi}"
: "${VM_NET_1_MAC:=001C42E11011}"
: "${VM_NET_1_IPV4_METHOD:=static}"
: "${VM_NET_1_IPV4_ADDRESS:=192.168.0.130/24}"
: "${VM_NET_1_IPV4_GATEWAY:=192.168.0.1}"
: "${VM_NET_1_IPV4_DNS:=192.168.0.1}"
: "${VM_NET_1_ROUTE_METRIC:=100}"
: "${VM_NET_1_NEVER_DEFAULT:=no}"

: "${VM_NET_2_NAME:=eth-hostonly}"
: "${VM_NET_2_TYPE:=host-only}"
: "${VM_NET_2_PRL_IFACE:=Host-Only}"
: "${VM_NET_2_MAC:=001C42E11012}"
: "${VM_NET_2_IPV4_METHOD:=disabled}"
: "${VM_NET_2_IPV4_ADDRESS:=}"
: "${VM_NET_2_IPV4_GATEWAY:=}"
: "${VM_NET_2_IPV4_DNS:=}"
: "${VM_NET_2_ROUTE_METRIC:=300}"
: "${VM_NET_2_NEVER_DEFAULT:=yes}"
