#!/usr/bin/env bash

: "${VM_USERNAME:=ajm}"
: "${VM_CPUS:=4}"
: "${VM_MEMORY_MB:=8192}"
: "${VM_DISK_GB:=120}"
: "${VM_TIMEZONE:=Europe/London}"
: "${VM_KEYBOARD_LAYOUT:=gb}"
: "${VM_KEYBOARD_MODEL:=pc105}"
: "${VM_KEYBOARD_VARIANT:=mac_intl}"
: "${VM_KEYBOARD_OPTIONS:=}"
: "${VM_KEYBOARD_VC_KEYMAP:=gb-mac_intl}"
: "${VM_CHRONY_MAKESTEP:=1.0 3}"
: "${VM_PACKAGE_UPGRADE:=false}"
: "${VM_PACKAGE_REBOOT_IF_REQUIRED:=false}"
: "${VM_BOOT_PARTITION_GB:=}"
: "${VM_DISABLE_FIREWALLD:=true}"
: "${VM_INSTALL_SSH_CONFIG:=false}"
: "${VM_BOOT_IMAGE_ARCHIVE:=${VM_TARGET_DIR}/base.hdd.tar.zst}"
: "${VM_IMAGE_ARTIFACTS_URL_ARM64:=https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/aarch64/images/}"
: "${VM_IMAGE_ARTIFACTS_URL_AMD64:=https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/}"
: "${VM_IMAGE_NAME_REGEX:=Fedora-Cloud-Base-Generic-[^\"]*\\.${VM_ARCH}\\.qcow2}"
: "${VM_CHECKSUM_NAME_REGEX:=Fedora-Cloud-[^\"]*-CHECKSUM}"
: "${VM_PRL_DISTRIBUTION:=fc}"

: "${VM_NET_COUNT:=1}"

: "${VM_NET_0_NAME:=eth-shared}"
: "${VM_NET_0_TYPE:=shared}"
: "${VM_NET_0_PRL_IFACE:=}"
: "${VM_NET_0_MAC:=}"
: "${VM_NET_0_IPV4_METHOD:=dhcp}"
: "${VM_NET_0_IPV4_ADDRESS:=}"
: "${VM_NET_0_IPV4_GATEWAY:=}"
: "${VM_NET_0_IPV4_DNS:=}"
: "${VM_NET_0_ROUTE_METRIC:=100}"
: "${VM_NET_0_NEVER_DEFAULT:=no}"
