#!/usr/bin/env bash

: "${VM_NAME:=fedora}"
: "${VM_HOSTNAME:=fedora}"
: "${VM_FQDN:=fedora.ajm.dev}"
: "${VM_USERNAME:=ajm}"
: "${VM_CPUS:=8}"
: "${VM_MEMORY_MB:=16384}"
: "${VM_DISK_GB:=300}"
: "${VM_TIMEZONE:=Europe/London}"
: "${VM_KEYBOARD_LAYOUT:=gb}"
: "${VM_KEYBOARD_MODEL:=pc105}"
: "${VM_KEYBOARD_VARIANT:=mac_intl}"
: "${VM_KEYBOARD_OPTIONS:=}"
: "${VM_KEYBOARD_VC_KEYMAP:=gb-mac_intl}"
: "${VM_K8S_CHANNEL:=v1.35}"
: "${VM_CHRONY_MAKESTEP:=1.0 3}"
